# Generated by rust2rpm 21
%bcond_without check
%global debug_package %{nil}

%global crate bevy

Name:           rust-%{crate}
Version:        0.7.0
Release:        %autorelease
Summary:        Refreshingly simple data-driven game engine and app framework

# Upstream license specification: MIT OR Apache-2.0
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/bevy
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Refreshingly simple data-driven game engine and app framework.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%license %{crate_instdir}/docs/LICENSE-APACHE
%license %{crate_instdir}/docs/LICENSE-MIT
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/CODE_OF_CONDUCT.md
%doc %{crate_instdir}/CONTRIBUTING.md
%doc %{crate_instdir}/CREDITS.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+animation-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+animation-devel %{_description}

This package contains library source intended for building other packages which
use the "animation" feature of the "%{crate}" crate.

%files       -n %{name}+animation-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+basis-universal-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+basis-universal-devel %{_description}

This package contains library source intended for building other packages which
use the "basis-universal" feature of the "%{crate}" crate.

%files       -n %{name}+basis-universal-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bevy_animation-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bevy_animation-devel %{_description}

This package contains library source intended for building other packages which
use the "bevy_animation" feature of the "%{crate}" crate.

%files       -n %{name}+bevy_animation-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bevy_audio-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bevy_audio-devel %{_description}

This package contains library source intended for building other packages which
use the "bevy_audio" feature of the "%{crate}" crate.

%files       -n %{name}+bevy_audio-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bevy_ci_testing-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bevy_ci_testing-devel %{_description}

This package contains library source intended for building other packages which
use the "bevy_ci_testing" feature of the "%{crate}" crate.

%files       -n %{name}+bevy_ci_testing-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bevy_core_pipeline-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bevy_core_pipeline-devel %{_description}

This package contains library source intended for building other packages which
use the "bevy_core_pipeline" feature of the "%{crate}" crate.

%files       -n %{name}+bevy_core_pipeline-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bevy_dylib-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bevy_dylib-devel %{_description}

This package contains library source intended for building other packages which
use the "bevy_dylib" feature of the "%{crate}" crate.

%files       -n %{name}+bevy_dylib-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bevy_dynamic_plugin-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bevy_dynamic_plugin-devel %{_description}

This package contains library source intended for building other packages which
use the "bevy_dynamic_plugin" feature of the "%{crate}" crate.

%files       -n %{name}+bevy_dynamic_plugin-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bevy_gilrs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bevy_gilrs-devel %{_description}

This package contains library source intended for building other packages which
use the "bevy_gilrs" feature of the "%{crate}" crate.

%files       -n %{name}+bevy_gilrs-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bevy_gltf-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bevy_gltf-devel %{_description}

This package contains library source intended for building other packages which
use the "bevy_gltf" feature of the "%{crate}" crate.

%files       -n %{name}+bevy_gltf-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bevy_pbr-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bevy_pbr-devel %{_description}

This package contains library source intended for building other packages which
use the "bevy_pbr" feature of the "%{crate}" crate.

%files       -n %{name}+bevy_pbr-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bevy_render-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bevy_render-devel %{_description}

This package contains library source intended for building other packages which
use the "bevy_render" feature of the "%{crate}" crate.

%files       -n %{name}+bevy_render-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bevy_sprite-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bevy_sprite-devel %{_description}

This package contains library source intended for building other packages which
use the "bevy_sprite" feature of the "%{crate}" crate.

%files       -n %{name}+bevy_sprite-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bevy_text-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bevy_text-devel %{_description}

This package contains library source intended for building other packages which
use the "bevy_text" feature of the "%{crate}" crate.

%files       -n %{name}+bevy_text-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bevy_ui-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bevy_ui-devel %{_description}

This package contains library source intended for building other packages which
use the "bevy_ui" feature of the "%{crate}" crate.

%files       -n %{name}+bevy_ui-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bevy_winit-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bevy_winit-devel %{_description}

This package contains library source intended for building other packages which
use the "bevy_winit" feature of the "%{crate}" crate.

%files       -n %{name}+bevy_winit-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bmp-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bmp-devel %{_description}

This package contains library source intended for building other packages which
use the "bmp" feature of the "%{crate}" crate.

%files       -n %{name}+bmp-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+dds-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dds-devel %{_description}

This package contains library source intended for building other packages which
use the "dds" feature of the "%{crate}" crate.

%files       -n %{name}+dds-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+debug_asset_server-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+debug_asset_server-devel %{_description}

This package contains library source intended for building other packages which
use the "debug_asset_server" feature of the "%{crate}" crate.

%files       -n %{name}+debug_asset_server-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+dynamic-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dynamic-devel %{_description}

This package contains library source intended for building other packages which
use the "dynamic" feature of the "%{crate}" crate.

%files       -n %{name}+dynamic-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+filesystem_watcher-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+filesystem_watcher-devel %{_description}

This package contains library source intended for building other packages which
use the "filesystem_watcher" feature of the "%{crate}" crate.

%files       -n %{name}+filesystem_watcher-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+flac-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+flac-devel %{_description}

This package contains library source intended for building other packages which
use the "flac" feature of the "%{crate}" crate.

%files       -n %{name}+flac-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+hdr-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+hdr-devel %{_description}

This package contains library source intended for building other packages which
use the "hdr" feature of the "%{crate}" crate.

%files       -n %{name}+hdr-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+jpeg-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+jpeg-devel %{_description}

This package contains library source intended for building other packages which
use the "jpeg" feature of the "%{crate}" crate.

%files       -n %{name}+jpeg-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ktx2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ktx2-devel %{_description}

This package contains library source intended for building other packages which
use the "ktx2" feature of the "%{crate}" crate.

%files       -n %{name}+ktx2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mp3-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mp3-devel %{_description}

This package contains library source intended for building other packages which
use the "mp3" feature of the "%{crate}" crate.

%files       -n %{name}+mp3-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+png-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+png-devel %{_description}

This package contains library source intended for building other packages which
use the "png" feature of the "%{crate}" crate.

%files       -n %{name}+png-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+render-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+render-devel %{_description}

This package contains library source intended for building other packages which
use the "render" feature of the "%{crate}" crate.

%files       -n %{name}+render-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serialize-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serialize-devel %{_description}

This package contains library source intended for building other packages which
use the "serialize" feature of the "%{crate}" crate.

%files       -n %{name}+serialize-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+subpixel_glyph_atlas-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+subpixel_glyph_atlas-devel %{_description}

This package contains library source intended for building other packages which
use the "subpixel_glyph_atlas" feature of the "%{crate}" crate.

%files       -n %{name}+subpixel_glyph_atlas-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tga-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tga-devel %{_description}

This package contains library source intended for building other packages which
use the "tga" feature of the "%{crate}" crate.

%files       -n %{name}+tga-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+trace-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+trace-devel %{_description}

This package contains library source intended for building other packages which
use the "trace" feature of the "%{crate}" crate.

%files       -n %{name}+trace-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+trace_chrome-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+trace_chrome-devel %{_description}

This package contains library source intended for building other packages which
use the "trace_chrome" feature of the "%{crate}" crate.

%files       -n %{name}+trace_chrome-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+trace_tracy-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+trace_tracy-devel %{_description}

This package contains library source intended for building other packages which
use the "trace_tracy" feature of the "%{crate}" crate.

%files       -n %{name}+trace_tracy-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+vorbis-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+vorbis-devel %{_description}

This package contains library source intended for building other packages which
use the "vorbis" feature of the "%{crate}" crate.

%files       -n %{name}+vorbis-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wav-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wav-devel %{_description}

This package contains library source intended for building other packages which
use the "wav" feature of the "%{crate}" crate.

%files       -n %{name}+wav-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wayland-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wayland-devel %{_description}

This package contains library source intended for building other packages which
use the "wayland" feature of the "%{crate}" crate.

%files       -n %{name}+wayland-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wgpu_trace-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wgpu_trace-devel %{_description}

This package contains library source intended for building other packages which
use the "wgpu_trace" feature of the "%{crate}" crate.

%files       -n %{name}+wgpu_trace-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+x11-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+x11-devel %{_description}

This package contains library source intended for building other packages which
use the "x11" feature of the "%{crate}" crate.

%files       -n %{name}+x11-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+zlib-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+zlib-devel %{_description}

This package contains library source intended for building other packages which
use the "zlib" feature of the "%{crate}" crate.

%files       -n %{name}+zlib-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+zstd-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+zstd-devel %{_description}

This package contains library source intended for building other packages which
use the "zstd" feature of the "%{crate}" crate.

%files       -n %{name}+zstd-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
